/**
 * Wision55
 * API per l'utilizzo dei servizi della piattaforma Wision55
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CardVO {
    id?: number;

    attivo?: boolean;

    codice?: string;

    pin?: string;

    secretKey?: string;

    clienteId?: number;

    numero_cellulare?: string;

    meccanismo_protezione?: CardVO.MeccanismoProtezioneEnum;

}
export namespace CardVO {
    export enum MeccanismoProtezioneEnum {
        PinTotale = <any> 'pin_totale',
        PinParziale = <any> 'pin_parziale',
        TOtp = <any> 't_otp',
        HOtp = <any> 'h_otp',
        CodiceSms = <any> 'codice_sms'
    }
}
