/**
 * Wision55
 * API per l'utilizzo dei servizi della piattaforma Wision55
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PosVO {
    id?: number;

    attivo?: boolean;

    negozioId?: number;

    username?: string;

    password?: string;

    repeat?: string;

    etichetta?: string;

    isp?: string;

    ip?: string;

    cap?: string;
    
    indirizzo?: string;

    comune?: string;

    provincia?: string;

    nazione?: string;

}
